repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: poetry run black .
        pass_filenames: false
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: system
        entry: poetry run isort .
        args: ["--profile=black"]
        pass_filenames: false
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint  --recursive=y .
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
  - repo: local
    hooks:
      - id: export
        name: export
        language: system
        entry: sh ./export_requirements.sh